[SERVICE]
    Flush     1
    Log_Level info

[INPUT]
    Name    dummy
    Tag     fluentbit.connectivity
    Dummy   {"message":"fluent-bit-to-fluentd"}
    Samples 1

[OUTPUT]
    Name  forward
    Match fluentbit.connectivity
    Host  forwarder
    Port  24224
